export type FieldType = "text" | "textarea" | "date" | "number" | "select";

export interface FieldDef {
  name: string;
  label: string;
  type?: FieldType;
  options?: string[];
  list?: boolean; // show in table
  student?: boolean; // searchable student picker
  generated?: boolean; // generated by the database; never entered manually
  lookupCategory?: string; // user-customisable options
}

export interface RecordConfig {
  key: string;
  table: string;
  title: string;
  singular: string;
  fields: FieldDef[];
}

export const DOMAINS = ["وقائي", "إنمائي", "علاجي", "تنظيمي", "أكاديمي", "سلوكي", "اجتماعي", "نفسي", "صحي"];
export const PRIORITIES = ["منخفضة", "متوسطة", "عالية"];
export const EXEC_STATUS = ["لم يبدأ", "قيد التنفيذ", "مكتمل", "مؤجل"];
export const DOC_STATUS = ["ناقص", "قيد المراجعة", "معتمد"];
export const CHANNELS = ["مقابلة", "اتصال هاتفي", "رسالة نصية", "واتساب", "بريد إلكتروني", "زيارة منزلية"];
export const STAGES = ["ابتدائي", "متوسط", "ثانوي"];
export const EVIDENCE_TYPES = ["PDF", "صورة", "تقرير", "كشف حضور", "محضر"];
export const PROGRAM_TYPES = ["وقائي", "إنمائي", "علاجي"];
export const REFERRAL_SOURCES = ["الطالب نفسه", "ولي الأمر", "المعلم", "إدارة المدرسة", "لجنة التوجيه الطلابي", "ملاحظة الموجه"];
export const REFERRAL_REASONS = ["صعوبات أكاديمية", "غياب أو تأخر متكرر", "مشكلة سلوكية", "مشكلة نفسية", "مشكلة اجتماعية أو أسرية", "مشكلة صحية", "حماية من الإيذاء", "احتياج تربوي خاص"];
export const INTERNAL_REFERRAL_DESTINATIONS = ["إدارة المدرسة", "وكيل شؤون الطلاب", "لجنة التوجيه الطلابي", "المعلم", "المرشد الصحي"];
export const EXTERNAL_REFERRAL_DESTINATIONS = ["وحدة الخدمات الإرشادية", "وحدة الرعاية الطلابية", "إدارة التعليم", "المركز الصحي", "جهة صحية", "جهة أمنية", "جهة مختصة"];
export const REFERRAL_DESTINATIONS = [...INTERNAL_REFERRAL_DESTINATIONS, ...EXTERNAL_REFERRAL_DESTINATIONS];
export const INTERVENTIONS = ["مقابلة فردية", "جلسة إرشاد جمعي", "تواصل مع ولي الأمر", "خطة تعديل سلوك", "متابعة أكاديمية", "إحالة لجهة مختصة", "تنسيق مع المعلمين", "متابعة دورية"];

const notes: FieldDef = { name: "notes", label: "ملاحظات", type: "textarea" };

export const RECORDS: RecordConfig[] = [
  {
    key: "students",
    table: "students",
    title: "سجل الطلاب",
    singular: "طالب",
    fields: [
      { name: "student_no", label: "رقم الطالب" },
      { name: "full_name", label: "اسم الطالب", list: true },
      { name: "national_id", label: "رقم الهوية", list: true },
      { name: "nationality", label: "الجنسية", list: true },
      { name: "gender", label: "الجنس", type: "select", options: ["ذكر", "أنثى"] },
      { name: "stage", label: "المرحلة", type: "select", options: STAGES },
      { name: "grade", label: "الصف", list: true },
      { name: "classroom", label: "الفصل", list: true },
      { name: "guardian_name", label: "ولي الأمر", list: true },
      { name: "guardian_phone", label: "جوال ولي الأمر", list: true },
      { name: "address", label: "السكن" },
      { name: "health_status", label: "الحالة الصحية", type: "textarea" },
      { name: "social_status", label: "الحالة الاجتماعية", type: "textarea" },
      { name: "status", label: "الحالة", type: "select", options: ["نشط", "منقول", "منقطع"] },
      notes,
    ],
  },
  {
    key: "cases",
    table: "counseling_cases",
    title: "الحالات الإرشادية",
    singular: "حالة",
    fields: [
      { name: "case_no", label: "رقم الحالة", list: true, generated: true },
      { name: "student_no", label: "رقم الطالب" },
      { name: "student_name", label: "اسم الطالب", list: true, student: true },
      { name: "domain", label: "المجال", type: "select", options: DOMAINS, list: true, lookupCategory: "domains" },
      { name: "referral_source", label: "مصدر الإحالة", type: "select", options: REFERRAL_SOURCES, lookupCategory: "referral_sources" },
      { name: "case_status", label: "حالة الحالة", type: "select", options: ["مفتوحة", "قيد المتابعة", "مغلقة"], list: true, lookupCategory: "case_statuses" },
      { name: "priority", label: "الأولوية", type: "select", options: PRIORITIES, list: true, lookupCategory: "priorities" },
      { name: "summary", label: "ملخص الحالة", type: "textarea" },
      { name: "intervention_plan", label: "خطة التدخل", type: "select", options: INTERVENTIONS, lookupCategory: "interventions" },
      { name: "opened_at", label: "تاريخ الفتح", type: "date" },
      { name: "followup_at", label: "موعد المتابعة", type: "date", list: true },
      { name: "last_followup", label: "آخر متابعة", type: "date" },
      { name: "next_action", label: "الإجراء القادم" },
      { name: "closed_at", label: "تاريخ الإغلاق", type: "date" },
      notes,
    ],
  },
  {
    key: "plan",
    table: "plan_tasks",
    title: "الخطة التشغيلية",
    singular: "مهمة",
    fields: [
      { name: "seq", label: "رقم", list: true },
      { name: "task", label: "المهمة/النشاط", list: true },
      { name: "domain", label: "المجال", type: "select", options: DOMAINS, list: true },
      { name: "target_group", label: "الفئة المستهدفة" },
      { name: "term", label: "الفصل الدراسي" },
      { name: "indicator", label: "المؤشر/المعيار" },
      { name: "exec_status", label: "حالة التنفيذ", type: "select", options: EXEC_STATUS, list: true },
      { name: "doc_status", label: "حالة التوثيق", type: "select", options: DOC_STATUS, list: true },
      { name: "required_evidence", label: "الشواهد المطلوبة" },
      { name: "due_date", label: "تاريخ الاستحقاق", type: "date", list: true },
      { name: "done_date", label: "تاريخ التنفيذ", type: "date" },
      notes,
    ],
  },
  {
    key: "programs",
    table: "programs",
    title: "البرامج والأنشطة",
    singular: "برنامج",
    fields: [
      { name: "program_no", label: "رقم البرنامج", list: true },
      { name: "name", label: "اسم البرنامج", list: true },
      { name: "ptype", label: "النوع", type: "select", options: PROGRAM_TYPES, list: true },
      { name: "domain", label: "المجال", type: "select", options: DOMAINS },
      { name: "target_group", label: "الفئة المستهدفة", list: true },
      { name: "term", label: "الفصل الدراسي" },
      { name: "goal", label: "الهدف", type: "textarea" },
      { name: "indicator", label: "المؤشر" },
      { name: "start_date", label: "تاريخ البداية", type: "date" },
      { name: "end_date", label: "تاريخ النهاية", type: "date" },
      { name: "exec_status", label: "حالة التنفيذ", type: "select", options: EXEC_STATUS, list: true },
      { name: "beneficiaries", label: "عدد المستفيدين", type: "number", list: true },
      { name: "required_evidence", label: "الشواهد المطلوبة" },
      notes,
    ],
  },
  {
    key: "interviews",
    table: "interviews",
    title: "المقابلات والتواصل",
    singular: "مقابلة",
    fields: [
      { name: "seq", label: "رقم السجل" },
      { name: "idate", label: "التاريخ", type: "date", list: true },
      { name: "itype", label: "النوع", type: "select", options: ["مقابلة فردية", "مقابلة جماعية", "ولي أمر", "معلم"], list: true },
      { name: "student_no", label: "رقم الطالب" },
      { name: "student_name", label: "اسم الطالب", list: true, student: true },
      { name: "participant", label: "المشارك/ولي الأمر" },
      { name: "channel", label: "وسيلة التواصل", type: "select", options: CHANNELS, list: true, lookupCategory: "channels" },
      { name: "topic", label: "موضوع اللقاء", list: true },
      { name: "result", label: "النتيجة", type: "textarea" },
      { name: "recommendations", label: "التوصيات", type: "textarea" },
      { name: "followup_at", label: "موعد المتابعة", type: "date" },
      { name: "evidence_url", label: "الشاهد/الرابط" },
      notes,
    ],
  },
  {
    key: "attendance",
    table: "attendance",
    title: "الحضور والمواظبة",
    singular: "سجل مواظبة",
    fields: [
      { name: "seq", label: "رقم السجل" },
      { name: "student_no", label: "رقم الطالب" },
      { name: "student_name", label: "اسم الطالب", list: true, student: true },
      { name: "adate", label: "التاريخ", type: "date", list: true },
      { name: "case_type", label: "نوع الحالة", type: "select", options: ["غياب", "تأخر", "هروب", "غياب بعذر"], list: true },
      { name: "count_days", label: "عدد الأيام/المرات", type: "number", list: true },
      { name: "action", label: "الإجراء الإرشادي", list: true },
      { name: "guardian_name", label: "ولي الأمر" },
      { name: "evidence_url", label: "الشاهد/الرابط" },
      notes,
    ],
  },
  {
    key: "behavior",
    table: "behavior",
    title: "السلوك والمتابعة",
    singular: "مخالفة",
    fields: [
      { name: "seq", label: "رقم السجل" },
      { name: "student_no", label: "رقم الطالب" },
      { name: "student_name", label: "اسم الطالب", list: true, student: true },
      { name: "bdate", label: "التاريخ", type: "date", list: true },
      { name: "observation", label: "الملاحظة/المخالفة", list: true },
      { name: "referral_source", label: "مصدر الإحالة", type: "select", options: REFERRAL_SOURCES, lookupCategory: "referral_sources" },
      { name: "action", label: "الإجراء", type: "select", options: INTERVENTIONS, list: true, lookupCategory: "interventions" },
      { name: "result", label: "النتيجة", type: "select", options: ["تحسن", "تحسن جزئي", "تحتاج متابعة", "تمت الإحالة", "أغلقت الحالة"], list: true, lookupCategory: "behavior_results" },
      { name: "followup_at", label: "موعد المتابعة", type: "date" },
      { name: "evidence_url", label: "الشاهد/الرابط" },
      notes,
    ],
  },
  {
    key: "referrals",
    table: "referrals",
    title: "سجل الإحالات",
    singular: "إحالة",
    fields: [
      { name: "referral_no", label: "رقم الإحالة", list: true },
      { name: "case_no", label: "رقم الحالة المرتبطة" },
      { name: "student_no", label: "رقم الطالب" },
      { name: "student_name", label: "اسم الطالب", list: true, student: true },
      { name: "referral_date", label: "تاريخ الإحالة", type: "date", list: true },
      { name: "referred_to", label: "الجهة المحال إليها", type: "select", options: REFERRAL_DESTINATIONS, list: true, lookupCategory: "referral_destinations" },
      { name: "reason", label: "سبب الإحالة / المبررات", type: "textarea", lookupCategory: "referral_reasons" },
      { name: "attachments", label: "الإجراءات السابقة والمستندات المرفقة", type: "textarea" },
      { name: "status", label: "الحالة", type: "select", options: ["مرسلة", "قيد المتابعة", "منتهية"], list: true },
      { name: "reply_date", label: "تاريخ الرد", type: "date" },
      { name: "result", label: "نتيجة الإحالة", type: "select", options: ["قبول الإحالة", "إعادة للمدرسة", "خطة علاجية", "متابعة مشتركة", "إغلاق الإحالة"], lookupCategory: "referral_results" },
      notes,
    ],
  },
  {
    key: "committees",
    table: "committees",
    title: "اللجان والاجتماعات",
    singular: "اجتماع",
    fields: [
      { name: "seq", label: "رقم" },
      { name: "mdate", label: "التاريخ", type: "date", list: true },
      { name: "meeting_type", label: "نوع الاجتماع", type: "select", options: ["لجنة التوجيه الطلابي", "لجنة الحالات", "اجتماع أولياء الأمور", "اجتماع المعلمين"], list: true, lookupCategory: "meeting_types" },
      { name: "attendees", label: "الحضور", type: "textarea" },
      { name: "topic", label: "موضوع الاجتماع", list: true },
      { name: "decisions", label: "القرارات والتوصيات", type: "textarea", list: true },
      { name: "responsible", label: "المسؤول" },
      { name: "due_date", label: "موعد التنفيذ", type: "date" },
      { name: "evidence_url", label: "الشاهد/المحضر" },
      notes,
    ],
  },
  {
    key: "evidences",
    table: "evidences",
    title: "الشواهد والتوثيق",
    singular: "شاهد",
    fields: [
      { name: "seq", label: "رقم الشاهد" },
      { name: "name", label: "اسم الشاهد", list: true },
      { name: "etype", label: "نوع الشاهد", type: "select", options: EVIDENCE_TYPES, list: true },
      { name: "linked_type", label: "مرتبط بنوع", type: "select", options: ["برنامج", "حالة", "مقابلة", "اجتماع", "مهمة"], list: true },
      { name: "linked_ref", label: "رقم السجل المرتبط" },
      { name: "edate", label: "تاريخ الشاهد", type: "date", list: true },
      { name: "doc_status", label: "حالة التوثيق", type: "select", options: DOC_STATUS, list: true },
      { name: "file_url", label: "رابط/مسار الملف" },
      { name: "description", label: "وصف الشاهد", type: "textarea" },
      { name: "reviewed_by", label: "تمت المراجعة بواسطة" },
      notes,
    ],
  },
  {
    key: "reports",
    table: "reports",
    title: "سجل التقارير",
    singular: "تقرير",
    fields: [
      { name: "report_no", label: "رقم التقرير", list: true },
      { name: "report_type", label: "نوع التقرير", type: "select", options: ["التقرير الشهري", "تقرير الفصل الدراسي", "التقرير الختامي", "تقرير برنامج"], list: true },
      { name: "period", label: "الفترة", list: true },
      { name: "report_date", label: "تاريخ التقرير", type: "date", list: true },
      { name: "prepared_by", label: "المُعد" },
      { name: "status", label: "الحالة", type: "select", options: ["مسودة", "معتمد", "مرسل"], list: true },
      { name: "summary", label: "ملخص التقرير / خلاصة الحالة", type: "textarea" },
      { name: "file_url", label: "الرابط/الملف" },
      notes,
    ],
  },
  {
    key: "calendar",
    table: "calendar_events",
    title: "التقويم والمتابعة",
    singular: "موعد",
    fields: [
      { name: "seq", label: "رقم" },
      { name: "edate", label: "التاريخ", type: "date", list: true },
      { name: "etime", label: "الوقت", list: true },
      { name: "title", label: "المهمة/الموعد", list: true },
      { name: "etype", label: "النوع", type: "select", options: ["متابعة", "مقابلة", "برنامج", "اجتماع", "تقرير"], list: true },
      { name: "linked_ref", label: "مرتبط بسجل" },
      { name: "priority", label: "الأولوية", type: "select", options: PRIORITIES, list: true },
      { name: "status", label: "حالة الموعد", type: "select", options: ["مجدول", "منفذ", "مؤجل", "ملغي"], list: true },
      notes,
    ],
  },
];

export const recordByKey = (key: string) => RECORDS.find((r) => r.key === key)!;
