import { createFileRoute,Link } from "@tanstack/react-router";
import { useQuery,useQueryClient } from "@tanstack/react-query";
import { CheckCircle2,Clock3,FileCheck2,XCircle,ArrowLeft } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/_authenticated/guidance-approvals")({component:Page,head:()=>({meta:[{title:"اعتمادات التوجيه | الذات"}]})});
const statusLabel:Record<string,string>={submitted:"بانتظار المراجعة",reviewed:"تمت المراجعة",approved:"معتمد",rejected:"معاد/مرفوض"};
function Page(){const qc=useQueryClient();
 const ctx=useQuery({queryKey:["my-guidance-workspace"],queryFn:async()=>{const {data,error}=await (supabase as any).rpc("get_my_guidance_workspace");if(error)throw error;return data as any}});
 const q=useQuery({queryKey:["guidance-approvals"],queryFn:async()=>{const {data,error}=await (supabase as any).from("guidance_approvals").select("*").order("submitted_at",{ascending:false});if(error)throw error;return data??[]}});
 const role=String(ctx.data?.role||"");const canReview=Boolean(ctx.data?.is_admin)||["counselor","student_affairs_vice","principal"].includes(role);const canDecide=Boolean(ctx.data?.is_admin)||["student_affairs_vice","principal"].includes(role);
 const act=async(id:string,action:string)=>{const notes=window.prompt(action==="approved"?"ملاحظات الاعتماد (اختياري):":"اكتب الملاحظة:")||null;const {error}=await (supabase as any).rpc("review_guidance_approval",{p_approval_id:id,p_action:action,p_notes:notes});if(error)return toast.error(error.message);await qc.invalidateQueries({queryKey:["guidance-approvals"]});toast.success(action==="approved"?"تم الاعتماد.":action==="rejected"?"تمت إعادة العمل بالملاحظة.":"تمت المراجعة.")};
 const rows=q.data||[],pending=rows.filter((x:any)=>x.status==="submitted").length,reviewed=rows.filter((x:any)=>x.status==="reviewed").length,approved=rows.filter((x:any)=>x.status==="approved").length;
 return <div dir="rtl" className="space-y-5"><section className="rounded-3xl border bg-card p-5"><h1 className="text-2xl font-black">اعتمادات أعمال التوجيه</h1><p className="mt-1 text-xs text-muted-foreground">مراجعة الأعمال المرفوعة واعتمادها أو إعادتها بملاحظة، حسب صلاحية الدور ومستوى السرية.</p></section>
 <section className="grid grid-cols-3 gap-3"><Stat icon={<Clock3 className="size-4"/>} label="بانتظار المراجعة" value={pending}/><Stat icon={<FileCheck2 className="size-4"/>} label="تمت مراجعتها" value={reviewed}/><Stat icon={<CheckCircle2 className="size-4"/>} label="معتمدة" value={approved}/></section>
 <section className="space-y-3">{rows.map((a:any)=><article key={a.id} className="rounded-2xl border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{a.title}</strong><p className="mt-1 text-[11px] text-muted-foreground">{a.item_type} · {a.confidentiality==="restricted"?"مقيد وسري":a.confidentiality==="guidance"?"خاص بالتوجيه":"فريق العمل"}</p></div><span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-black text-primary">{statusLabel[a.status]||a.status}</span></div>{a.notes&&<p className="mt-3 text-sm">{a.notes}</p>}{a.review_notes&&<div className="mt-3 rounded-xl bg-muted/60 p-3 text-xs"><b>ملاحظة المراجع:</b> {a.review_notes}</div>}<div className="mt-3 flex flex-wrap gap-2">{canReview&&a.status==="submitted"&&<Button size="sm" variant="outline" onClick={()=>act(a.id,"reviewed")}>تسجيل المراجعة</Button>}{canDecide&&["submitted","reviewed"].includes(a.status)&&<><Button size="sm" onClick={()=>act(a.id,"approved")}><CheckCircle2 className="size-4"/>اعتماد</Button><Button size="sm" variant="destructive" onClick={()=>act(a.id,"rejected")}><XCircle className="size-4"/>إعادة بملاحظة</Button></>}</div></article>)}{!q.isLoading&&rows.length===0&&<div className="rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">لا توجد أعمال مرفوعة للاعتماد حاليًا.</div>}</section>
 <Button asChild variant="outline"><Link to="/guidance-work">العودة لأعمال التوجيه <ArrowLeft className="size-4"/></Link></Button></div>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-2xl border bg-card p-3"><div className="flex items-center justify-between text-primary">{icon}<b className="text-xl">{value}</b></div><p className="mt-2 text-[10px] font-bold">{label}</p></div>}