import { createFileRoute } from "@tanstack/react-router";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Send,ClipboardList } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
export const Route=createFileRoute("/_authenticated/guidance-requests")({component:Page,head:()=>({meta:[{title:"طلبات التوجيه | الذات"}]})});
function Page(){
 const qc=useQueryClient();const [kind,setKind]=useState("referral"),[student,setStudent]=useState(""),[category,setCategory]=useState(""),[subject,setSubject]=useState(""),[details,setDetails]=useState(""),[urgency,setUrgency]=useState("normal");
 const ctx=useQuery({queryKey:["guidance-request-context"],queryFn:async()=>{const {data,error}=await (supabase as any).rpc("get_my_guidance_workspace");if(error)throw error;return data as any}});
 const q=useQuery({queryKey:["guidance-requests"],queryFn:async()=>{const {data,error}=await (supabase as any).from("guidance_requests").select("*").order("created_at",{ascending:false});if(error)throw error;return data??[]}});
 const save=useMutation({mutationFn:async()=>{const {error}=await (supabase as any).rpc("submit_guidance_request",{p_student_id:null,p_student_name:student.trim()||null,p_kind:kind,p_category:category.trim()||null,p_subject:subject.trim(),p_details:details.trim(),p_urgency:urgency,p_confidentiality:"guidance"});if(error)throw error},onSuccess:async()=>{setStudent("");setCategory("");setSubject("");setDetails("");await qc.invalidateQueries({queryKey:["guidance-requests"]});toast.success("تم إرسال الطلب للموجه الطلابي.")},onError:e=>toast.error((e as Error).message)});
 const canManage=Boolean(ctx.data?.permissions?.manage)||["counselor","principal"].includes(String(ctx.data?.role||""));
 const respond=async(id:string,status:string)=>{const response=window.prompt("ملاحظة أو رد على الطلب (اختياري):")||null;const {error}=await (supabase as any).rpc("respond_guidance_request",{p_request_id:id,p_status:status,p_response:response});if(error)return toast.error(error.message);await qc.invalidateQueries({queryKey:["guidance-requests"]});toast.success("تم تحديث الطلب.")};
 return <div dir="rtl" className="space-y-5"><section className="rounded-3xl border bg-card p-5"><div className="flex items-center gap-3"><ClipboardList className="size-6 text-primary"/><div><h1 className="text-xl font-black">طلبات التوجيه الطلابي</h1><p className="text-xs text-muted-foreground">إحالة طالب أو تسجيل ملاحظة أو طلب استشارة، مع متابعة الحالة دون كشف ملفات التوجيه الأخرى.</p></div></div></section>
 <section className="rounded-3xl border bg-card p-5"><h2 className="mb-4 font-black">طلب جديد</h2><div className="grid gap-3 sm:grid-cols-2">
 <div><Label>نوع الطلب</Label><select className="mt-2 h-11 w-full rounded-xl border bg-background px-3" value={kind} onChange={e=>setKind(e.target.value)}><option value="referral">إحالة طالب</option><option value="observation">ملاحظة على طالب</option><option value="consultation">طلب استشارة</option></select></div>
 <div><Label>الطالب</Label><Input className="mt-2" value={student} onChange={e=>setStudent(e.target.value)} placeholder="اسم الطالب"/></div>
 <div><Label>التصنيف</Label><Input className="mt-2" value={category} onChange={e=>setCategory(e.target.value)} placeholder="سلوكي، نفسي، اجتماعي، تحصيلي..."/></div>
 <div><Label>الأهمية</Label><select className="mt-2 h-11 w-full rounded-xl border bg-background px-3" value={urgency} onChange={e=>setUrgency(e.target.value)}><option value="normal">عادي</option><option value="important">مهم</option><option value="urgent">عاجل</option></select></div>
 <div className="sm:col-span-2"><Label>الموضوع</Label><Input className="mt-2" value={subject} onChange={e=>setSubject(e.target.value)}/></div><div className="sm:col-span-2"><Label>التفاصيل</Label><Textarea className="mt-2 min-h-28" value={details} onChange={e=>setDetails(e.target.value)}/></div></div><Button className="mt-4" disabled={!subject.trim()||!details.trim()||save.isPending} onClick={()=>save.mutate()}><Send className="size-4"/>إرسال للموجه الطلابي</Button></section>
 <section className="rounded-3xl border bg-card p-5"><h2 className="mb-3 font-black">{canManage?"الوارد من أعضاء المدرسة":"طلباتي السابقة"}</h2><div className="space-y-2">{(q.data||[]).map((r:any)=><article key={r.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><strong>{r.subject}</strong><p className="mt-1 text-xs text-muted-foreground">{r.student_name||"بدون طالب محدد"} · {r.category||"غير مصنف"}</p></div><span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-black text-primary">{r.status}</span></div><p className="mt-3 text-sm leading-6">{r.details}</p>{r.response&&<div className="mt-3 rounded-xl bg-muted/50 p-3 text-xs"><b>الرد:</b> {r.response}</div>}{canManage&&r.status!=="completed"&&<div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>respond(r.id,"reviewed")}>تمت المراجعة</Button><Button size="sm" variant="outline" onClick={()=>respond(r.id,"in_progress")}>قيد المعالجة</Button><Button size="sm" onClick={()=>respond(r.id,"completed")}>إكمال وإغلاق</Button><Button size="sm" variant="destructive" onClick={()=>respond(r.id,"rejected")}>رفض</Button></div>}</article>)}{!q.isLoading&&(q.data||[]).length===0&&<p className="text-center text-sm text-muted-foreground">لا توجد طلبات حتى الآن.</p>}</div></section></div>
}