export { AppLayout } from "./components/AppLayout"
export { Copyright } from "./components/Copyright"
export { EvidenceUploadDialog, EvidenceGallery } from "./components/EvidenceUpload"
export { StudentsImportDialog } from "./components/StudentsImportDialog"
export { OfficialHeader, OfficialFooter } from "./components/OfficialHeader"
export { PlanGate } from "./components/PlanGate"
export { RecordAttachmentsDialog } from "./components/RecordAttachments"
export { RecordPage } from "./components/RecordPage"
export { RecordPrintDialog } from "./components/RecordPrintDialog"
export { SignaturePad } from "./components/SignaturePad"
export { StudentCombobox } from "./components/StudentCombobox"
export { StudentsPage } from "./components/StudentsPage"
export { ThemePicker } from "./components/ThemePicker"
export { WhatsAppButton } from "./components/WhatsAppButton"
export { AlertDialog, AlertDialogPortal, AlertDialogOverlay, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogFooter, AlertDialogTitle, AlertDialogDescription, AlertDialogAction, AlertDialogCancel } from "./components/ui/alert-dialog"
export { Button } from "./components/ui/button"
export { Dialog, DialogPortal, DialogOverlay, DialogTrigger, DialogClose, DialogContent, DialogHeader, DialogFooter, DialogTitle, DialogDescription } from "./components/ui/dialog"
export { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuRadioItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuGroup, DropdownMenuPortal, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuRadioGroup } from "./components/ui/dropdown-menu"
export { Input } from "./components/ui/input"
export { Label } from "./components/ui/label"
export { Popover, PopoverTrigger, PopoverContent, PopoverAnchor } from "./components/ui/popover"
export { Textarea } from "./components/ui/textarea"
export { Constants } from "./integrations/supabase/types"
export { ThemeProvider } from "./lib/theme"
