-- Production data protection: recycle bin + immutable audit trail.
-- Every client DELETE on core user-owned records is copied here before removal.

create table if not exists public.deleted_records (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  table_name text not null,
  record_id uuid,
  record_data jsonb not null,
  deleted_at timestamptz not null default now(),
  deleted_by uuid
);

create index if not exists deleted_records_user_deleted_idx
  on public.deleted_records (user_id, deleted_at desc);

alter table public.deleted_records enable row level security;

drop policy if exists "users_read_own_deleted_records" on public.deleted_records;
create policy "users_read_own_deleted_records"
on public.deleted_records for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "users_remove_own_deleted_records" on public.deleted_records;
create policy "users_remove_own_deleted_records"
on public.deleted_records for delete to authenticated
using (auth.uid() = user_id);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  actor_id uuid,
  action text not null check (action in ('INSERT','UPDATE','DELETE','RESTORE')),
  table_name text not null,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  changed_at timestamptz not null default now()
);

create index if not exists audit_log_user_changed_idx
  on public.audit_log (user_id, changed_at desc);

alter table public.audit_log enable row level security;

drop policy if exists "users_read_own_audit_log" on public.audit_log;
create policy "users_read_own_audit_log"
on public.audit_log for select to authenticated
using (auth.uid() = user_id);

create or replace function public.capture_deleted_record()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.deleted_records (
    user_id, table_name, record_id, record_data, deleted_by
  )
  values (
    old.user_id,
    tg_table_name,
    nullif(to_jsonb(old)->>'id','')::uuid,
    to_jsonb(old),
    auth.uid()
  );
  return old;
end;
$$;

create or replace function public.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  payload jsonb;
  owner_id uuid;
  row_id text;
begin
  payload := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  owner_id := nullif(payload->>'user_id','')::uuid;
  row_id := payload->>'id';

  if owner_id is not null then
    insert into public.audit_log (
      user_id, actor_id, action, table_name, record_id, old_data, new_data
    )
    values (
      owner_id,
      auth.uid(),
      tg_op,
      tg_table_name,
      row_id,
      case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
      case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end
    );
  end if;

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create or replace function public.restore_deleted_record(p_deleted_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  item public.deleted_records%rowtype;
  restored_id uuid;
begin
  select *
  into item
  from public.deleted_records
  where id = p_deleted_id
    and user_id = auth.uid();

  if not found then
    raise exception 'Deleted record not found or not accessible';
  end if;

  if item.table_name not in (
    'students','counseling_cases','interviews','attendance','behavior',
    'referrals','committees','plan_tasks','programs','evidences',
    'calendar_events','reports','posts'
  ) then
    raise exception 'Restore is not allowed for table %', item.table_name;
  end if;

  if nullif(item.record_data->>'user_id','')::uuid is distinct from auth.uid() then
    raise exception 'Record owner mismatch';
  end if;

  execute format(
    'insert into public.%I select * from jsonb_populate_record(null::public.%I, $1)',
    item.table_name,
    item.table_name
  ) using item.record_data;

  restored_id := nullif(item.record_data->>'id','')::uuid;

  insert into public.audit_log (
    user_id, actor_id, action, table_name, record_id, old_data, new_data
  )
  values (
    item.user_id, auth.uid(), 'RESTORE', item.table_name,
    restored_id::text, null, item.record_data
  );

  delete from public.deleted_records where id = item.id;
  return restored_id;
end;
$$;

revoke all on function public.restore_deleted_record(uuid) from public;
grant execute on function public.restore_deleted_record(uuid) to authenticated;

do $$
declare
  t text;
begin
  foreach t in array array[
    'students','counseling_cases','interviews','attendance','behavior',
    'referrals','committees','plan_tasks','programs','evidences',
    'calendar_events','reports','posts'
  ]
  loop
    if to_regclass('public.' || t) is not null then
      execute format('drop trigger if exists recycle_bin_before_delete on public.%I', t);
      execute format(
        'create trigger recycle_bin_before_delete before delete on public.%I for each row execute function public.capture_deleted_record()',
        t
      );
      execute format('drop trigger if exists audit_user_changes on public.%I', t);
      execute format(
        'create trigger audit_user_changes after insert or update or delete on public.%I for each row execute function public.write_audit_log()',
        t
      );
    end if;
  end loop;
end $$;